[colors.primary]
background = "#282634"
foreground = "#c5c8c6"

[env]
WINIT_HIDPI_FACTOR = "1"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10

[font.normal]
family = "DejaVu Sans Mono"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"
